
language: cpp
dist: bionic

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

matrix:
  exclude:
    - os: osx
      arch:
       - arm64
       - ppc64le
       - s390x

addons:
  apt:
    packages:
      - libxml2-dev
      - libpng-dev
      - libjpeg-dev
      - libjpeg-turbo8
      - sqlite3
      - libsqlite-dev
      - libsigc++-2.0-dev
      - libfreetype6-dev
  homebrew:
    packages:
      - libsigc++@2
      - libtool
      - freetype
    update: true

before_script:
  - mkdir build; cd build; cmake ..

script: make


