
language: cpp
dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

arch:
  - amd64
  - arm64

matrix:
  exclude:
    - os: osx
      arch: arm64

addons:
  apt:
    packages:
      - libxml2-dev
      - libpng12-dev
      - libjpeg-dev
      - libjpeg-turbo8
      - sqlite3
      - libsqlite-dev
      - libsigc++-2.0-dev
      - libfreetype6-dev
  homebrew:
    packages:
      - libsigc++@2
      - libtool
      - freetype
    update: true

before_script:
  - ./autogen.sh --verbose 
  - ./configure

script: make && make test


