
language: cpp
dist: trusty

addons:
  apt:
    packages:
      - libxml2-dev
      - libpng12-dev
      - libjpeg-dev
      - libjpeg-turbo8
      - sqlite3
      - libsqlite-dev
      - libsigc++-2.0-dev
  homebrew:
    packages:
      - libsigc++
      - libtool

before_script:
  - ./autogen.sh --verbose 
  - ./configure

script: make && make test

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

